kind: "Compute"
version: "1"
data:
  services:
    - name: first-compute
    - name: second-compute
  # Uncomment to enable secrets
  # secrets:
  #   - key: API_TOKEN
  #     value: ${{ API_TOKEN_SECRET }}
